### ISSUE TITLE
Make a NuGet?

### ISSUE THREAD

**Issue by MarcWeintraub** [kjpgit/SmallestCSVParser#1]
I'd love to see this as a NuGet package. Also, do you plan on making any enhancements to it or keep as slim as possible?

**Comment by kjpgit** [comment]
I'd be happy to try to push it to nuget.  Was just waiting for someone to ask.  

As far as enhancements, this is intended to be a low level parser that follows the RFC.   So it depends what you're asking for.  But I could certainly add examples of ways to build higher level abstractions.

**Comment by kjpgit** [comment]
This is on nuget now.  Thanks for the request.
